INSERT INTO [dbo].[Cars](
      [Car_Brand],
      [Car_Status],
      [Car_ID]
)
VALUES
('ES','Lexus', 2017),
('LC500H','Lexus', 2018),
('RC','Lexus', 2015),
('RX','Lexus', 2018),
('IS300','Lexus', 2004),
('ISF','Lexus', 2008),
('IS250','Lexus', 2016),
('IS350','Lexus', 2018),
('SupraA90','Toyota', 2019),
('GR86','Toyota', 2022),
('Supra','Toyota', 1997),
('YarisY20','Toyota', 2019);